package com.hospital.gateway.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.UnsupportedJwtException;
import io.jsonwebtoken.security.Keys;
import io.jsonwebtoken.security.SignatureException;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.security.Key;
import java.util.Date;

/**
 * JWT Token Provider
 * ==================
 * Responsible for all JWT token operations within the API Gateway.
 * The gateway only needs to VALIDATE tokens (not create them), since
 * token generation is handled by the Auth Service.
 *
 * This provider uses the same shared secret key as all other microservices
 * to ensure tokens generated by the Auth Service can be validated here.
 *
 * Extracted claims:
 *   - email (subject)     : The authenticated user's email address
 *   - role  (custom claim): The user's role (PATIENT, DOCTOR, ADMIN)
 */
@Component
@Slf4j
public class JwtTokenProvider {

    @Value("${jwt.secret}")
    private String jwtSecret;

    @Value("${jwt.expiration}")
    private long jwtExpiration;

    // The cryptographic signing key derived from the secret string
    private Key signingKey;

    /**
     * Initialize the signing key after dependency injection is complete.
     * Converts the string secret into an HMAC-SHA key suitable for JJWT.
     */
    @PostConstruct
    public void init() {
        this.signingKey = Keys.hmacShaKeyFor(jwtSecret.getBytes());
        log.info("JWT Token Provider initialized for API Gateway");
    }

    /**
     * Validates a JWT token by attempting to parse it.
     * Checks signature validity, expiration, and structural correctness.
     *
     * @param token the JWT token string to validate
     * @return true if the token is valid, false otherwise
     */
    public boolean validateToken(String token) {
        try {
            Jwts.parserBuilder()
                    .setSigningKey(signingKey)
                    .build()
                    .parseClaimsJws(token);
            return true;
        } catch (SignatureException e) {
            log.error("Invalid JWT signature: {}", e.getMessage());
        } catch (MalformedJwtException e) {
            log.error("Malformed JWT token: {}", e.getMessage());
        } catch (ExpiredJwtException e) {
            log.error("Expired JWT token: {}", e.getMessage());
        } catch (UnsupportedJwtException e) {
            log.error("Unsupported JWT token: {}", e.getMessage());
        } catch (IllegalArgumentException e) {
            log.error("JWT claims string is empty: {}", e.getMessage());
        }
        return false;
    }

    /**
     * Extracts the user's email address from the JWT token.
     * The email is stored as the token's "subject" claim.
     *
     * @param token the JWT token string
     * @return the email address of the authenticated user
     */
    public String getEmailFromToken(String token) {
        Claims claims = extractAllClaims(token);
        return claims.getSubject();
    }

    /**
     * Extracts the user's role from the JWT token.
     * The role is stored as a custom "role" claim (e.g., PATIENT, DOCTOR, ADMIN).
     *
     * @param token the JWT token string
     * @return the role of the authenticated user
     */
    public String getRoleFromToken(String token) {
        Claims claims = extractAllClaims(token);
        return claims.get("role", String.class);
    }

    /**
     * Extracts the user's ID from the JWT token.
     * The user ID is stored as a custom "userId" claim.
     *
     * @param token the JWT token string
     * @return the user ID of the authenticated user
     */
    public String getUserIdFromToken(String token) {
        Claims claims = extractAllClaims(token);
        return claims.get("userId", String.class);
    }

    /**
     * Parses the JWT token and extracts all claims.
     * This is a private helper used by all public extraction methods.
     *
     * @param token the JWT token string
     * @return the Claims object containing all token claims
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parserBuilder()
                .setSigningKey(signingKey)
                .build()
                .parseClaimsJws(token)
                .getBody();
    }
}
