package com.hospital.auth.entity;

import com.hospital.auth.enums.Role;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * ============================================================================
 * User Entity - MongoDB Document
 * ============================================================================
 * Represents a user account in the Hospital Appointment System. This document
 * is stored in the "users" collection within the auth_db MongoDB database.
 *
 * The email field is indexed with a unique constraint to prevent duplicate
 * registrations and to speed up login lookups.
 *
 * Password is stored as a BCrypt-encoded hash — never in plain text.
 * The createdAt timestamp records when the account was first created.
 * ============================================================================
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "users")
public class User {

    /**
     * Unique identifier for the user, auto-generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * User's email address. Serves as the unique login identifier.
     * Indexed for fast lookup during authentication and uniqueness enforcement.
     */
    @Indexed(unique = true)
    private String email;

    /**
     * BCrypt-encoded password hash. Never stored or transmitted in plain text.
     */
    private String password;

    /**
     * User's display name (e.g., "Dr. John Smith" or "Jane Doe").
     */
    private String name;

    /**
     * The role assigned to this user, determining their access level.
     * One of: ADMIN, DOCTOR, or PATIENT.
     */
    private Role role;

    /**
     * Timestamp recording when this user account was created.
     */
    private LocalDateTime createdAt;
}
