package com.hospital.doctor.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * ============================================================================
 * Doctor Entity - MongoDB Document
 * ============================================================================
 * Represents a doctor in the Hospital Appointment System.
 * Stored in the "doctors" collection in MongoDB (doctor_db).
 *
 * Fields:
 * - id:              Auto-generated MongoDB ObjectId
 * - name:            Full name of the doctor
 * - specialization:  Medical specialization (e.g., CARDIOLOGY, NEUROLOGY)
 * - email:           Unique email address (indexed for fast lookups)
 * - phone:           Contact phone number
 * - availability:    Whether the doctor is currently available (default: true)
 * - createdAt:       Timestamp when the doctor record was created
 * ============================================================================
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "doctors")
public class Doctor {

    /** Unique identifier - auto-generated by MongoDB */
    @Id
    private String id;

    /** Full name of the doctor */
    private String name;

    /** Medical specialization (matches Specialization enum values) */
    @Indexed
    private String specialization;

    /** Email address - unique identifier for the doctor, indexed for fast lookups */
    @Indexed(unique = true)
    private String email;

    /** Contact phone number */
    private String phone;

    /** Availability status - defaults to true when a new doctor is registered */
    @Builder.Default
    private boolean availability = true;

    /** Timestamp of when the doctor record was created, auto-populated by MongoDB auditing */
    @CreatedDate
    private LocalDateTime createdAt;
}
